// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Prefer environment variables (Vite) for production safety.
const ENV_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as
  | string
  | undefined;
const ENV_SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as
  | string
  | undefined;

// Keep legacy URL fallback (non-secret) for convenience
const LEGACY_SUPABASE_URL = "https://cffqeonmtdetcthutyfb.supabase.co";

export const SUPABASE_URL = ENV_SUPABASE_URL || LEGACY_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY = ENV_SUPABASE_KEY || "";

if (!ENV_SUPABASE_KEY) {
  if (!import.meta.env.DEV) {
    // In production, require env var to be set — fail fast to avoid using missing/incorrect key
    throw new Error(
      "[supabase] VITE_SUPABASE_ANON_KEY must be set in production environment"
    );
  }
   
  console.warn(
    "[supabase] VITE_SUPABASE_ANON_KEY is not set. Set it in .env for local development."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
